<script>
	var tags = [];
<?php 
	$tags = $this->tags;
	
	// Create a JS array with the tag data for the auto complete feature
	foreach ($tags as $c) { 
		?> tags.push( "<?=$c->getName()?>" ); 
	<?php 
	}
	?>
</script>
<?php 	
	$t = $this->technologies;
	$c = $this->companies;
?>

<div class="wrapp">

	<?php 
	if ($this->addedItem) {
		echo "<div class='overlay'>";
			echo "<div class='ccbox mainwrapper'>";
			echo "<h2><strong>Wissen erfolgreich hinzugefügt!</strong></h2>";
			echo "</div>";
		echo "</div>";
	}
	?>

    <div style="margin-bottom:20px;" class="ccbox mainwrapper">
    	<h2>Neues Wissen hinzufügen</h2>
    	
    	<form action="" method="post" id="new">	    	
    		<label>Firma</label>
	    	<select name="company">
	    		<option value="-1">---</option>
	    	<?php
	    		foreach ($c as $company) 
				{
					echo "<option value=" . $company->getId() . ">" .
						$company->getName() . "</option>";
				} 
	    	?>
	    	</select>	    
	    		    	    	
	    	<br>
	    	
    		<label>Technologie</label>
	    	<select name="technology">
	    		<option value="-1">---</option>
	    	<?php
	    		foreach ($t as $technology) 
				{
					echo "<option value=" . $technology->getId() . ">" .
						$technology->getName() . "</option>";
				} 
	    	?>
	    	</select>	
	    	
	    	<br>
	    	<br>
	    	<label>Beschreibung<br><textarea rows="5" cols="51" name="content"></textarea></label>
	    	<br>
	    	<br>
	    	<label>Tags (mit Kommata trennen)<br><input id="tags" class="taginputs" name="tags"></label>
		</form>
		
	    <br>
	    <button type="submit" form="new">Wissen speichern</button>	
    </div>
    
</div>
<?php  $this->headScript()
            ->appendFile($this->basePath() . '/js/jquery-ui.js')?>