<script>
	var tags = [];
<?php 
	$tags = $this->tags;
	
	// Create a JS array with the tag data for the auto complete feature
	foreach ($tags as $c) { 
		?> tags.push( "<?=$c->getName()?>" ); 
	<?php 
	}
	?>
</script>
<?php
	$a = $this->assignees; 
	$t = $this->technologies;
	$c = $this->companies;
?>

<div class="wrapp">

    <div style="margin-bottom:20px;" class="ccbox mainwrapper">
    	<h2><strong>Aufgabe erstellen</strong></h2>
    	<br>
    	
    	<form action="" method="post" id="new">
    		<label>Firma</label>
	    	<select name="company" class="comp">
	    		<option value="-1">---</option>
	    	<?php
	    		foreach ($c as $company) 
				{
					echo "<option value=" . $company->getId() . ">" .
						$company->getName() . "</option>";
				} 
	    	?>
	    	</select>	    	
	    	    	
	    	<br>
	    	
    		<label>Technologie</label>
	    	<select name="technology" class='tech'>
	    		<option value="-1">---</option>
	    	<?php
	    		foreach ($t as $technology) 
				{
					echo "<option value='{$technology->getId()}'>{$technology->getName()}</option>";
				} 
	    	?>
	    	</select>	
	    	
	    	<br>
	    	<br>
	    	<br>
	    	<label>Beschreibung<br><textarea rows="5" cols="51" name="content"></textarea></label>
	    	<br>
	    	<br>
	    	<label>Tags (mit Kommata trennen)<br><input id="tags" class="taginputs" name="tags"></label>	    	
	    	<br>
	    	<br>
	    	<label>Zuweisen an:</label>
	    	<select name="assignee">
	    		<option value="-1">---</option>
	    	<?php
	    		foreach ($a as $person) 
				{
					echo "<option value=" . $person->getId() . ">" .
						$person->getFirstname() . " " . $person->getLastname() . "</option>";
				} 
	    	?>
	    	</select>
		</form>
		
	    <br>
	    <button type="submit" form="new">Aufgabe erstellen</button>	
<!-- 	    <button type="button" id="getRec" >Empfehlung generieren</button> -->
    </div>
    
	<div class="rec-div ccbox mainwrapper">	    	
		<h2><strong>Empfehlungen</strong></h2>
    	<br>
    	
		<ul class="rec-list">
		</ul>
	</div>
</div>
<?php  $this->headScript()
            ->appendFile($this->basePath() . '/js/jquery-ui.js')?>