<div class="wrapp">

    <div style="margin-bottom:20px;" class="ccbox mainwrapper">
    	<h2>Problemstellung</h2>
      	
      	<div class="left">
      		<h3>Kunde</h3>
      			<select>
					<option>Tincidunt Congue Company</option>
					<option>Quis Turpis Vitae Company</option>
					<option>Etiam Corporation</option>
					<option>optionistique Incorporated</option>
				</select>
      	</div>
      	
      	<div class="left">
      		<h3>Produkt</h3>
      			<select>
					<option value="1">Webseite</option>
					<option value="2">Online-Anwendung</option>
				</select>
      	</div>
      	
      	<div class="left">
      		<h3>Problem</h3>
      			<select>
					<option value="1">Seite kann nicht gefunden werden</option>
					<option value="2">Schriften werden nicht richtig angezeigt</option>
					<option value="3">Falsche Formatierung</option>
					<option value="4">Suchfunktion funktioniert nicht</option>
				</select>
		</div>
    </div>
        
    <div class="ccbox mainwrapper">
    	<h2>Empfehlungen</h2>
    	<ul class="nav nav-tabs" role="tablist">
	        <li class="active"><a href="#">JavaScript</a></li>
	        <li><a href="#">PHP</a></li>
	        <li><a href="#">CSS</a></li>
	        <li><a href="#">TYPO3</a></li>
	        <li><a href="#">Magento</a></li>
	        <li><a href="#">Wordpress</a></li>
	        <li><a href="#">HTML</a></li>
      	</ul>
      	
      	<div class="recommendations-wrapper left">
      		<div class="recommendation">
      			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur est sem, cursus vel est a, vehicula vulputate turpis. Etiam et purus est. Vestibulum consequat ex pellentesque feugiat viverra. Aenean fringilla efficitur lacinia. Maecenas efficitur felis eget diam tempus, at imperdiet nisi ullamcorper. Aliquam sit amet eros at purus finibus vestibulum vitae
      			</p>
      		</div>
      	</div>  
      	    	
      	<div class="recommendations-wrapper left">
      		<div class="recommendation">
      			<p>id nisi. Pellentesque lacinia eget sapien vel molestie. Fusce in quam malesuada, fringilla nisi quis, lobortis turpis. Proin aliquet erat ut magna mattis rhoncus
      			</p>
      		</div>
      	</div>
      	
      	<div class="recommendations-wrapper left">
      		<div class="recommendation">
      			<p>Quisque sodales risus et magna ornare, ac sollicitudin nulla accumsan. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec et fermentum eros, sed pulvinar elit.
      			</p>
      		</div>
      	</div>
      	
      	<div class="recommendations-wrapper left">
      		<div class="recommendation">
      			<p>Etiam quis malesuada urna. Suspendisse potenti. Nulla facilisi. Nulla feugiat tellus neque, ut fringilla ipsum pretium sit amet. Integer sed urna et enim
      			</p>
      		</div>
      	</div>
      	
      	
    </div>
</div>