<?php 
	$currentPostsNumber = $this->currentPosts;	
	$recentPostsPreview = $this->preview;

?>

<div class="wrapp index">

	<div class="linkbox" data-link="<?php echo $this->url("add-item")?>">
		<h3>Neues Wissen</h3>
		
		<p>Hast du etwas beizutragen? <strong>Pflege neues Wissen ein!</strong></p>
		<br>
		<br>
		<p>Beiträge im System: <strong><?php echo $currentPostsNumber ?></strong></p>
	</div>
	
	<div style="position: absolute;bottom: 150px;">
		<?php foreach ($recentPostsPreview as $k) 
		{
			echo '<div data-link="' . $this->url("item", array("id" => $k->getId())) . '" class="linkbox left">';
			echo '<h3>' . $k->getTechnology() . '</h3>';
			
			echo '<p>' . $k->getContent() . '</p>';
			
			echo '</div>';
		}
		?>
	</div>
	
</div>