<?php 
	$k = $this->item;
	
	if (method_exists($k, "setSolution")) {
		$type = "task";
	} else {
		$type = "knowledge";
	}
	
	$text = $k->getDescription();
	$user = $this->user;

	$fav = "false";
	foreach ($user->getFavorites()->toArray() as $key => $value) {
		$value->toString() != $k->getId() ?: $fav = "true";
	}
?>
<div class="wrapp opentask">
	<?php  
	if (isset($_SESSION["searchQuery"]) && isset($this->ref)) 
    { 
        echo "<form class='backresults' method='POST' action='../results'>";
    	echo "<input name='query' value='{$_SESSION['searchQuery']}' hidden=''><button type='submit' class='tag'><-- Zu den Suchergebnissen</button> </form>";
    }
	?>

    <div style="margin-bottom:20px;" class="ccbox mainwrapper">    	
    	<h2>
    		<strong><?=$type=="task" ? "Aufgabenstellung" : "Wissen"?></strong>
    		<span class='favorite <?=$fav ?>'></span>
    	</h2>
 		<?php 
    	if (null !== $k->getTechnology()) {
			echo "<pre>Technologie: 	{$k->getTechnology()->getName()}</pre>";
		}
    	if (null !== $k->getCompany()) {
			echo "<pre>Firma: 			{$k->getCompany()->getName()}</pre>";
		}
		echo "<br>";
		echo "<h3>Aufgabenbeschreibung:</h3>";
		echo '<div class="recommendations-wrapper">';
			echo '<div class="recommendation">';
			echo "<pre>{$text}</pre>";
			echo "</div>"; 
		echo "</div>";
		?>
		<br>
		
    	<?php
    	if (null !== $k->getTags()) {
			echo "<h3>Tags:</h3>";
			
    		foreach ($k->getTags() as $t) {
				if ($t->getName() !== "") {
					echo "<form method='POST' id='{$t->getId()}' name='{$t->getId()}' action='../results' >";
					echo "<input name='query' value='{$t->getName()}' hidden>";
					echo "<button type='submit' class='tag'>{$t->getName()}</button> ";
					echo "</form>";
				}
			}
    	}
    	?>
    	<br>
    	<br>
    	<br>
    	<?php 
    		echo "<p class='small'>Erstellt am " . $k->getCreated()->format("d.m.Y H:i")
    			. " von {$k->getAuthor()->getFullname()}</p>"; 
    	?>
    		
    	<?php 
    	if ($k->getUpdated() != $k->getCreated() )
    	{
    		echo "<p class='small'>Zuletzt geändert am " . $k->getUpdated()->format("d.m.Y H:i")
    		. " von {$k->getAuthor()->getFullname()}</p>"; 
    	}	
    	?>
    </div>
    <?php 
    	if ($type == "task" && $k->getStatus() == 0) {
    		echo '<div class="ccbox mainwrapper">';
				echo "<h2><strong>Deine Lösung</strong></h2>";
	    		echo "<form method='post' id='solution-form'>";
		    		echo "<textarea name='solution' rows='5' cols='51'></textarea>";
		    		echo "<button type='submit' form='solution-form'>Aufgabe abschließen</button>";
		    	echo "</form>";
	    	echo "</div>";
	    	
	    } else if ($this->reviewItem) {
			echo '<div class="ccbox mainwrapper">';
				echo "<h2><strong>Bewertung</strong></h2>";
				echo "<h3>Lösung akzeptieren und Aufgabe abschließen</h3>";
				echo "<form method='post' id='accept-form'>";
					echo "<input hidden name='status' value='accept'>";
					echo "<button type='submit' form='accept-form'>Annehmen</button>";
				echo "</form>";
				
				echo "<br><br>";

				echo "<h3>Ablehnen, mit Begründung zurück zum Entwickler</h3>";
				echo "<form method='post' id='decline-form'>";
					echo "<input hidden name='status' value='decline'>";
					echo "<textarea name='problems' rows='5' cols='51'></textarea>";
					echo "<button type='submit' form='decline-form'>Ablehnen</button>";
				echo "</form>";				
			echo "</div>";
		}
   	 echo "</div>";
		/*
		 * LÖSUNG ANZEIGEN 
		 */	
    	if (isset($this->solution)) {
	   		echo '<div class="rec-div ccbox mainwrapper">';
	    	echo "<h2><strong>Lösung</strong></h2>";
			echo "<div class='solution'><pre>{$this->solution}</pre></div>";
			echo "<br><br><br>";
			echo "<p class='small'>Bearbeitet am {$k->getSolutiondate()->format("d.m.Y")} von {$k->getAssignee()->getFullname()}</p>";
			echo "</div>";
		}
		
		/*
		 * LOGIK FÜR EMPFEHLUNGEN
		 */
    	if (isset($this->reccs)) {
	   		echo '<div class="rec-div ccbox mainwrapper">';
		    	echo "<h2><strong>Empfehlungen</strong></h2>";
		    	foreach ($this->reccs as $r) {
					echo "<h3  style='float:left;'>Wertigkeit: {$r["score"]}</h3><h3 style='float:right;' class='usesolution'>Diese Lösung verwenden</h3>";
					echo "<div data-id='{$r["id"]}' class='recommendation'><p>{$r["description"]}</p></div>";
				}		
			echo "</div>";
		}			
		echo "<div class='overlay unbreakable' style='display:none;'>";
			echo "<div class='ccbox mainwrapper'>";
			echo "<h2><strong>Wird bearbeitet..</strong></h2>";
			echo "</div>";
		echo "</div>";
		
		/*
		 * PROBLEME ANZEIGEN
		 */
    	if (isset($this->problems)) {
	   		echo '<div class="rec-div ccbox mainwrapper">';
	    		echo "<h2><strong>Probleme</strong></h2>";
				echo "<div class='solution'><pre>{$this->problems}</pre></div>";
				echo "<p class='small'>Kommentiert am " . $k->getProblemsDate()->format("d.m.Y H:i")
				. " von {$k->getAuthor()->getFullname()}</p>";
			echo "</div>";
		}
	?>
</div>    