<?php 
	$k = $this->item;
	
	if (method_exists($k, "getContent")) {
		$text = $k->getContent();
	} else {
		$text = $k->getDescription();
	}
	
?>

<div class="wrapp">

    <div style="margin-bottom:20px;" class="ccbox mainwrapper">
    	<h2><?php echo $k->getTechnology()->getName(); ?></h2>	
    	
    	<?php 
    	if (null !== $k->getCompany()) {
			echo "<h3>" . $k->getCompany()->getName() . "</h3>";
		}
    	?>			
    	<?php 
    			echo '<div class="recommendations-wrapper">';
				echo '<div class="recommendation">';
				
				echo '<p>' . $text . '</p>';
				
				echo '</div></div>';
		?>
		<br>
    	<h3>
    	<?php 

    	if (null !== $k->getTags()) {
    		foreach ($k->getTags() as $t) {
				echo $t->getName() . " ";
			}
    	}
    	?>
    	</h3>
    	<br>
    	<br>
    	<?php 
    		echo "<p class='small'>Erstellt am " . $k->getCreated()->format("d.m.Y H:i")
    			. " von <strong>" . $k->getAuthor()->getFullname() .  "</strong></p>"; 
    	?>
    		
    	<?php 
    	if ($k->getUpdated() != $k->getCreated() )
    	{
    		echo "<h3>Zuletzt geändert am " . $k->getUpdated()->format("d.m.Y H:i")
    		. " von <strong>Lars Schröer</strong></h3>";
    	}	
    	?>
    </div>
    
</div>