<?php 
	$k = $this->item;
	
	if (method_exists($k, "setSolution")) {
		$type = "task";
	} else {
		$type = "knowledge";
	}
	
	$text = $k->getDescription();
	
	$ferrors = $this->formErrors;
?>
<div class="wrapp opentask">
	<?php 
	if ($ferrors) 
	{
		foreach ($ferrors as $error) {
			echo "<p class='error'>{$error}</p>";
		}
	}             
	   
	if (isset($_SESSION["searchQuery"]) && isset($this->ref)) 
    { 
        echo "<form class='backresults' method='POST' action='../results'>";
    	echo "<input name='query' value='{$_SESSION['searchQuery']}' hidden=''><button type='submit' class='tag'><-- Zu den Suchergebnissen</button> </form>";
    }
	?>


    <div style="margin-bottom:20px;" class="ccbox mainwrapper">
    	
    	
    	<h2><strong><?=$type=="task" ? "Aufgabenstellung" : "Wissen"?></strong></h2>
 		<?php 
    	echo $k->getTechnology()->getName();
    	if (null !== $k->getCompany()) {
			echo " --- " . $k->getCompany()->getName();
		}
		echo '<div class="recommendations-wrapper">';
		echo '<div class="recommendation">';
		
		echo "<pre>{$text}</pre>";
		
		echo '</div></div>';
		?>
		<br>
		
    	<?php
    	if (null !== $k->getTags()) {
			echo "<h3>Tags:</h3>";
			
    		foreach ($k->getTags() as $t) {
				if ($t->getName() !== "") {
					echo "<form method='POST' id='{$t->getId()}' name='{$t->getId()}' action='../results' >";
					echo "<input name='query' value='{$t->getName()}' hidden>";
					echo "<button type='submit' class='tag'>{$t->getName()}</button> ";
					echo "</form>";
				}
			}
    	}
    	?>
    	<br>
    	<br>
    	<br>
    	<?php 
    		echo "<p class='small'>Erstellt am " . $k->getCreated()->format("d.m.Y H:i")
    			. " von {$k->getAuthor()->getFullname()}</p>"; 
    	?>
    		
    	<?php 
    	if ($k->getUpdated() != $k->getCreated() )
    	{
    		echo "<p class='small'>Zuletzt geändert am " . $k->getUpdated()->format("d.m.Y H:i")
    		. " von {$k->getAuthor()->getFullname()}</p>"; 
    	}	
    	?>
    </div>
    <?php 
    	if ($type == "task" && !$k->getStatus()) {
    		echo '<div class="ccbox mainwrapper">';
			echo "<h2><strong>Deine Lösung</strong></h2>";
    		echo "<form method='post' id='solution-form'>";
	    		echo "<textarea name='solution' rows='5' cols='51'></textarea>";
	    		echo "<br>";
	    		echo "<button type='submit' form='solution-form'>Aufgabe abschließen</button>";
	    	echo "</form>";
	    }
   	 echo "</div>";
    ?>
</div>    
    <?php 
    	if (isset($this->reccs)) {
	   		echo '<div class="rec-div ccbox mainwrapper">';
	    	echo "<h2><strong>Empfehlungen</strong></h2>";
	    	foreach ($this->reccs as $r) {
				echo "<h3  style='float:left;'>Wertigkeit: {$r["score"]}</h3><h3 style='float:right;' class='usesolution'>Diese Lösung verwenden</h3>";
				echo "<div data-id='{$r["id"]}' class='recommendation'><p>{$r["description"]}</p></div>";
			}		
			echo "<div class='overlay unbreakable' style='display:none;'>";
				echo "<div class='ccbox mainwrapper'>";
				echo "<h2><strong>Wird bearbeitet..</strong></h2>";
			echo "</div>";
		echo "</div>";
		}
		
    	if (isset($this->solution)) {
	   		echo '<div class="rec-div ccbox mainwrapper">';
	    	echo "<h2><strong>Lösung</strong></h2>";
			echo "<div class='solution'><pre>{$this->solution}</pre></div>";
		}
	?>